export interface Account {
  id: string;
  name: string;
  bankName: string;
  cardNumber: string;
  balance: number;
  smsSender?: string; // سرشماره پیامک بانک
  color: string;
}

export interface SmsPattern {
  id: string;
  bankName: string;
  accountId?: string; // ارتباط با حساب
  sender: string; // سرشماره ارسال‌کننده پیامک
  pattern: string;
  sampleMessage: string;
  amountRegex: string;
  type: 'credit' | 'debit' | 'both';
  approved: boolean;
  createdAt: string;
}

export interface Transaction {
  id: string;
  accountId: string;
  amount: number;
  type: 'income' | 'expense';
  category: string;
  description: string;
  date: string;
  isFixed: boolean;
  smsPatternId?: string;
}

export interface Debt {
  id: string;
  personName: string;
  amount: number;
  type: 'receivable' | 'payable';
  description: string;
  dueDate?: string;
  isPaid: boolean;
  createdAt: string;
}

export interface BudgetCategory {
  id: string;
  name: string;
  limit: number;
  spent: number;
  color: string;
}

export interface Budget {
  id: string;
  month: string;
  totalIncome: number;
  totalBudget: number;
  totalSpent: number;
  categories: BudgetCategory[];
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface AppData {
  accounts: Account[];
  smsPatterns: SmsPattern[];
  transactions: Transaction[];
  debts: Debt[];
  budgets: Budget[];
  hasScannedSms: boolean;
  theme: 'dark' | 'light';
}

export type TabType = 'dashboard' | 'sms' | 'accounts' | 'transactions' | 'debts' | 'budget';
